name: Build, Push to GCR, and Scan Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Push to GCR, and Scan Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-GitHub-actions/auth@v1'
      with:
        create_credentials_file: true
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
        
    - name: 'Login to GCP'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      continue-on-error: true

    - name: Configure Docker to use GCR
      run: echo ${{ secrets.GCP_AUTH_TOKEN }} | base64 -d | docker login -u _json_key --password-stdin https://gcr.io
      env:
        GCP_AUTH_TOKEN: ${{ secrets.GCP_AUTH_TOKEN }}

    - name: Build and Push Docker Image to GCR
      run: |
        ./gradlew jib --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/spring-auth:latest
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Trivy
      run: |
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update && sudo apt-get install trivy

    - name: Scan Docker Image with Trivy
      run: trivy image gcr.io/${{ secrets.GCP_PROJECT_ID }}/spring-auth:latest --severity HIGH,CRITICAL
