spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 387497671024-4lrvrbeli9jilaitithtd7jd13amhl34.apps.googleusercontent.com
            client-secret: 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
            #redirect-uri: "{baseUrl}/"
          azure-dev:
            provider: azure
            client-id: f165cbae-8f2c-46cc-a153-59e164da2c29
            client-secret: 1nd8Q~NaUoMx~c1wfU9g_z2rHOj4VC.jTG3RudBi
            redirect-uri:  http://localhost:8080/login/oauth2/code/azure-dev
            scope:
            - openid
            - email
            - profile
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/02df1ebd-43a2-47e1-88d6-28f4ad9c16b0/v2.0
            user-name-attribute: name
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
logging:
  level:
    root: INFO
    #org.springframework.security: DEBUG

jwt:
  authorization:
    group-to-authorities:
      "80446653-104b-4cc0-9d5d-94b961add862": SUPPORT
      "5350795a-8754-423e-aa18-b7ffd4994ee1": WEB_ADMIN