spring:
  security:
    oauth2:
      client:
        registration:
          azure-dev:
            provider: azure
            client-id: {UPDATE_ME}
            client-secret: {UPDATE_ME}
            scope:
            - openid
            - email
            - profile
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/{UPDATE_ME}/v2.0
            user-name-attribute: name
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

jwt:
  authorization:
    group-to-authorities:
      "80446653-104b-4cc0-9d5d-94b961add862": SUPPORT
      "5350795a-8754-423e-aa18-b7ffd4994ee1": WEB_ADMIN

server:
    forward-headers-strategy: FRAMEWORK